name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master # 或你希望觸發部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.24.1' # 根據需要選擇 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Connected to server"
            source ~/.zshrc
            nvm use v10.24.1
            node -v
            vue --version
            cd /var/www/html/jsy.tw/public/guand2019
            git pull origin master
            npm run build
            cp temp/.htaccess dist/
            cp temp/ads.txt dist/
